### ISSUE TITLE
로봇도 주 52시간 보장하라

### ISSUE THREAD

**Issue by jskimm** [arcadia-moon/ltrace#1]
보장하라 보장하라

**Comment by arcadia-moon** [comment]
여기서 이러시면 안됩니다 선생님.

**Comment by b4sh5i** [comment]
we will review and pass the issue directly.

**Comment by jskimm** [comment]
we will review and pass the issue directly.

**Comment by arcadia-moon** [comment]
![image](https://user-images.githubusercontent.com/41041877/145341153-3f0a2e9a-d746-41ae-8fc1-d2c04d1ee4b0.png)

@jskimm @b4sh5i
Korea해보겠습니다
